#!/bin/bash

# List each dmenu_ item in ~/.local/bin/dmenu
# Execute when selected

select_script() {
	file=$(printf "$(xclip -o)" | dmenu -i -p "Download:")

	youtube-dl --output '~/video/youtube/%title' $file
}

select_script
