#!/bin/bash

display=$(printf "external\\nextend\\ninternal\\nduplicate" | dmenu -i -p "Display: ")

internal() {
	xrandr --output LVDS \
	--primary \
	--auto
}

case $display in
	"external") echo "extersn";;
	"extend") echo "bdsfkdsfja";;
	"internal") echo "ajflkjalkf";;
esac

case "$1" in
	"external")
		external;;
	"internal")
		internal;;
	"extend")
		extend;;
	"duplicate")
		duplicate;;

